import Menu from "./Menu";
import Log from "./Logo";
import MenuMobile from "./MenuMobile";
import Hero from "./Hero";
import ItSWork from "./ItsWork";
import OurProject from "./OurProject";
import Features from "./Features";
import Slider from "./Slider";
import Faq from "./Faq";
import Blog from "./Blog";
import FooterContact from "./FooterContact";
import FooterMenu from "./FooterMenu";
FooterMenu();
FooterContact();
Menu();
Log();
MenuMobile();
Hero();
ItSWork();
OurProject();
Features();
Slider();
Faq();
Blog();
